### ISSUE TITLE
How to logon with username/password

### ISSUE THREAD

**Issue by supermartzin** [kpavlov/fixio#21]
Hi!

I would like to ask you if it is possible with Fixio to send `LOGON` request along with user credentials. So far I use `fixClient.connect()` method which has no option like that.

Thanks a lot.

**Comment by kpavlov** [comment]
Hello,

Right now there is no special way to do it other than modify LOGON message.
You may create a `fixio.handlers.FixMessageHandler` and implement method `fixio.handlers.FixMessageHandler.beforeSendMessage()` to modify LOGON message before it is being sent. You'll need to register this handler in `fixio.handlers.CompositeFixApplicationAdapter` which you'll pass to `FixClient` constructor. Or just override `fixio.handlers.FixApplicationAdapter.beforeSendMessage()`.

I hope this will help.
But support for Username & Password should be added to `fixio.netty.pipeline.client.ClientSessionHandler.createLogonRequest()`

**Comment by kpavlov** [comment]
Is it ok to store Username/Password in the `fixClient.properties` file or you prefer some AuthenticationProvider?

**Comment by supermartzin** [comment]
Thanks, 
in the meantime I figured it out just like you've just said :)
