### ISSUE TITLE
BodyLength and Checksum not set?

### ISSUE THREAD

**Issue by supermartzin** [kpavlov/fixio#22]
Hi!

I noticed during my testing that in message header there was no **`BodyLength`** tag which is required by the FIX Protocol specification (and I suspect this issue as a reason why I was being constantly disconnected from server).
Also **`Checksum`** tag in trailer is always set to 0, don't know if I have to set it somehow or it is a default value.

Thanks in advance for you help.

**Comment by kpavlov** [comment]
Sounds strange. `FixMessageEncoder` is calculating BodyLength and the CheckSum fields automatically. This is a last handler in the pipeline. Could you provide some details? Check the `fixio.FixConversationIT`.
