### ISSUE TITLE
fixio.fixprotocol.FieldType is absent

### ISSUE THREAD

**Issue by AlesPravdin** [kpavlov/fixio#23]
Just cloned from https://github.com/kpavlov/fixio.git. Can't see class fixio.fixprotocol.FieldType in repository.

**Comment by kpavlov** [comment]
This class is auto-generated from FIX 5.0 SP2 FIX dictionary from QuickFix
You may find it here: `core/target/generated-sources/java/fixio/fixprotocol/FieldType.java`
