### ISSUE TITLE
Is there any API documentation for fixio?

### ISSUE THREAD

**Issue by Hema-Chandra** [kpavlov/fixio#35]
I am very much new to the Stock exchange market. I just started looking into QuickFix  and when I am searching for that I found this project is very much useful for me. But I didn't found any API documentation. Can anyone provide me the documents, so that I can start as quick as possible. I will be very graceful if anyone can provide me  some more examples than they are already in the project source library. I have already worked with the examples in the library and I can able to see that, only a session is being created.After that nothing is being happening. Can anyone help me how can I place some orders from the initiator to the acceptor and again receive the response back? Some more examples with added order placing will help me a lot. I am very much interested in this project. I am really fed up with QuickFix latency and this the only thing that can help me a lot.   

I am also very much new to GitHub. And I am extremely sorry if this is the wrong place to ask such type of questions.

**Comment by kpavlov** [comment]
You need to construct order messages and send it to client. Also, you need to process response message in message handler.

**Comment by jvirtanen** [comment]
@Hema-Chandra If you are not specifically tied to Netty, you might be interested in giving [Philadelphia](https://github.com/paritytrading/philadelphia) a spin as as well.

**Comment by Hema-Chandra** [comment]
@jvirtanen  Thank you. I am not specifically tied to Netty. All I want is a very fast, low latency library. I have a small question. I have seen Philadelphia, and it seems quite interesting. Is this even faster than Netty?

**Comment by Hema-Chandra** [comment]
@kpavlov  Thank you sir. Is there any example for constructing order messages? I am really confused in how to construct. A small example can help me a lot sir.

**Comment by jvirtanen** [comment]
@Hema-Chandra Philadelphia is built on the Java NIO API, so you can directly poll the socket if you want. Furthermore, message reception, parsing, formatting, and transmission are all garbage-free operations. While real-world performance depends on the actual application, simple tests over the loopback interface indicate that Philadelphia's latency figures are close to those of [Libtrading](https://github.com/libtrading/libtrading), a low-latency FIX engine implemented as a C library.

**Comment by kpavlov** [comment]
You can create BUY market order as simple as this:
```
FixMessageBuilder newOrderSingle = new FixMessageBuilderImpl(MessageTypes.NEW_ORDER_SINGLE);
newOrderSingle.add(FieldType.ClOrdID, "1234");
newOrderSingle.add(FieldType.Side, '1');
newOrderSingle.add(FieldType.OrdType, '1');

newOrderSingle.add(FieldType.Symbol, symbol);
newOrderSingle.add(FieldType.TransactTime, System.currentTimeMillis());
```

**Comment by Hema-Chandra** [comment]
@kpavlov  Thank you very much sir.

**Comment by Hema-Chandra** [comment]
@jvirtanen  Thank you very much sir. And one last question. It is an open source library? so that I can just plug it into my code and can modify.

**Comment by jvirtanen** [comment]
@Hema-Chandra Yes, it's open source under the [Apache License, Version 2.0](https://github.com/paritytrading/philadelphia/blob/master/LICENSE.txt) and you are free to modify it to suit your needs.

**Comment by Hema-Chandra** [comment]
@jvirtanen Thank you very much sir
