### ISSUE TITLE
can not find FieldType class?

### ISSUE THREAD

**Issue by kouyusanpi** [kpavlov/fixio#40]
the source  code can not find FieldType class.

**Comment by kouyusanpi** [comment]
run

**Comment by kouyusanpi** [comment]
run “mvn clean install” ，bang! FieldType class  show！

**Comment by kpavlov** [comment]
Yes, this is generated class. Run: `mvn generate-sources`

**Comment by kouyusanpi** [comment]
Thank you very much! 
The FIXIO is very nice! 
Can i have your contacts?  I just started study FIX protocol. Can i ask you some question? 
And so sorry ,my english  is very poor.

**Comment by kpavlov** [comment]
No problem:) You may find my contacts here https://konstantinpavlov.net/about

**Comment by kouyusanpi** [comment]
Thank you sir!
I was Follow you on LinkedIn. my name is yubo(喻波).I am  Chinses.
I am programing FIX,The following question：
 Market Data Request: Subscription
8=FIX.4.3|9=205|35=V|34=177|49=quote.TestOrg.TestUser.dev|50=TestOrg|52=201402 2617:03:32.405|56=client.fxgrid.integral.com|128=Broker13|262=3ee|263=1|264=1| 265=0|146=1|55=EUR/USD|460=4|167=FOR|267=2|269=0|269=1|10=059|
the Subscription message has two  Tag:269, In the FIXIO that how can i do it.  The FixMessageBuilder is  Map type.

**Comment by kouyusanpi** [comment]
request: 
8=FIX.4.3|9=184|35=V|49=***|56=***|34=2|50=***|57=***|52=20180305-04:05:04.434|128=***|
262=161f4559330|263=1|264=1|265=0|146=1|55=EUR/USD|460=4|167=FOR|267=1|269=0|10=249|
response: 
8=FIX.4.3|9=164|35=Y|34=2|49=***|50=***|52=20180305-04:05:04.570|56=***|57=***|58=RequestValidationError.IncorrectMDEntryType|262=161f4559330|281=3|10=038

**Comment by kpavlov** [comment]
@kouyusanpi, please create separate issues next time
