### ISSUE TITLE
RequestValidationError.IncorrectMDEntryType

### ISSUE THREAD

**Issue by kpavlov** [kpavlov/fixio#42]
@kouyusanpi:
Request:
```8=FIX.4.3|9=184|35=V|49=***|56=***|34=2|50=***|57=***|52=20180305-04:05:04.434|128=***|262=161f4559330|263=1|264=1|265=0|146=1|55=EUR/USD|460=4|167=FOR|267=1|269=0|10=249|```

Response:
```8=FIX.4.3|9=164|35=Y|34=2|49=***|50=***|52=20180305-04:05:04.570|56=***|57=***|58=RequestValidationError.IncorrectMDEntryType|262=161f4559330|281=3|10=038```

See #40

**Comment by kouyusanpi** [comment]
Thank you sir!

**Comment by kouyusanpi** [comment]
The issue has has been solved.
I create new Class GroupFieldList,that the type is ArrayList data structure。

```
public class GroupFieldList implements FixMessageFragment<List<AbstractField>> {
    private static final int DEFAULT_SIZE = 2;
    private final List<AbstractField> groups;
    private final int tagNum;
```
FixMessageBuilderImpl class  add  method:
`
 public GroupFieldList newGroupFieldList(FieldType fieldType, int expectedGroupSize)
    {
        int tagNum = fieldType.tag();
        GroupFieldList g = (GroupFieldList) getFragment(tagNum);
        if (g == null) {
            g = new GroupFieldList(tagNum);
            body.put(tagNum, g);
        }
        return g;
    }
`
FixMessageEncoder class modify method encodeMessageFragment:


private static void encodeMessageFragment(ByteBuf payloadBuf,
                                              FixMessageFragment messageFragment) {
        if (messageFragment instanceof AbstractField) {
            writeField(messageFragment.getTagNum(), (AbstractField) messageFragment, payloadBuf);
        } else if (messageFragment instanceof GroupField) {
            GroupField groupField = (GroupField) messageFragment;
            writeField(groupField.getTagNum(), Integer.toString(groupField.getGroupCount()), payloadBuf);
            for (Group c : groupField.getValue()) {
                List<FixMessageFragment> contents = c.getContents();
                for (FixMessageFragment content : contents) {
                    encodeMessageFragment(payloadBuf, content);
                }
            }
        } else if (messageFragment instanceof GroupFieldList) {
            GroupFieldList groupField = (GroupFieldList) messageFragment;
            writeField(groupField.getTagNum(), Integer.toString(groupField.getGroupCount()), payloadBuf);
            for (FixMessageFragment c : groupField.getValue()) {
                    encodeMessageFragment(payloadBuf, c);
            }
        }
        
    }

**Comment by kpavlov** [comment]
Can't reproduce
