### ISSUE TITLE
Give a project more unique name.

### ISSUE THREAD

**Issue by kpavlov** [kpavlov/fixio#5]
> Also the name fixio? If you do a google search, you get lots of hits, something more unique would be preferred. maybe FIXMsgAPI

[comment](http://www.linkedin.com/groupItem?view=&gid=43143&item=5843614933815697410&type=member&commentID=discussion%3A5843614933815697410%3Agroup%3A43143&trk=hb_ntf_COMMENTED_ON_GROUP_DISCUSSION_YOU_CREATED#commentID_discussion%3A5843614933815697410%3Agroup%3A43143) by Robert J Wolf.

**Comment by guidomedina** [comment]
RxFIX maybe? If you add Java 8 new features and make everything asynchronous (which mostly is) and reactive, just throwing an idea.

**Comment by kpavlov** [comment]
RxFIX sounds better so far.

**Comment by kpavlov** [comment]
I created issue about migrating to java 8 https://github.com/kpavlov/fixio/issues/12. Let's continue the discussion there

**Comment by guidomedina** [comment]
ReactiveFIX? It is a bit longer but not that long, very explicit and will be more reachable via google.
